title: Neil the Seal
hero_image: images/banner.png
description: Code a game where you help Neil the seal waddle around town.
listed: false
pdf: false
steps:
  - title: Make Neil move
    completion:
      - engaged
  - title: Step title
  - title: Challenge
    challenge: true
    completion:
      - external
